### PR TITLE
Fix Source Journal Profile Report sample

### PR DESCRIPTION
**Pull request by brpak**

### CODE REVIEW

**Comment by jcthomas13** [comment]
hey Brian, Okay I see what you are doing here. But instead of a PowerShell script, we should simply deliver the exe file with the sample. Where does this exe reside when you copy it to the sample? For the other assets and other files, we include them in the solution wizard and deliver them this way. So, I guess it is important to know where this file will reside in the sample

**Comment by brpak** [comment]
The exe needs to be in the bin folder: Sage300-SDK\samples\SourceJournalProfilesReports\ValuedPartner.TU.Web\bin.
Should I remove the script and revert changes related to it?

**Comment by jcthomas13** [comment]
Hmmm. How does this exe get into the bin or Assemblies folder of the Dev solution?

**Comment by brpak** [comment]
Hey JT, I removed the powershell and included the .exe file in the reference

**Pull request merged**
